# Generated by Django 5.0.1 on 2024-02-23 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0002_task_tags_alter_tag_is_mode_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates if the task can be chosen today.', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date a task is created', verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='recurrance_in_seconds',
            field=models.FloatField(blank=True, help_text='Recurrance period in seconds', null=True, verbose_name='Recurrance in Seconds'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date a task starts', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.IntegerField(blank=True, help_text='Time spent on the task.', null=True, verbose_name='Time Spent'),
        ),
    ]
