# Generated by Django 5.0.1 on 2024-03-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0003_task_active_task_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='recurrance_in_seconds',
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_in_seconds',
            field=models.FloatField(blank=True, help_text='Recurrence period in seconds', null=True, verbose_name='Recurrence in Seconds'),
        ),
    ]
